### ISSUE TITLE
Unable to transpile ES6 > ES5

### ISSUE THREAD

**Issue by laicosly** [babel/gulp-babel#52]
```
Cannot find module 'core-js/library/fn/get-iterator'
```

This error is being thrown with the following stack when using presets: ["es2015"].  When not passing any options, the output file is not transpiled, it is an exact mirror of the original.

npm 2.14.7
node v4.2.1
gulp 4.0.0-alpha.1
gulp-babel  6.1.0

``` javascript
            return gulp.src([
                "./**/*.es6.js",
            ])
                .pipe(babel({
                    "presets": ["es2015"]
                }))
                .pipe(gulp.dest("./dist"))
```

**Comment by laicosly** [comment]
Manually entering my file contents onto the Babel "try it out" site, results in transpiled code.

https://babeljs.io/repl/

**Comment by laicosly** [comment]
gulp-traceur is working.

**Comment by trevoro** [comment]
I'm getting this same issue on my install.
The only difference is that I've upgraded `gulp-babel` to `6.1.0` from the `5.x.x` major version.
Nothing in the API seems to have changed. I am also using `gulpfile.babel.js`.

**Comment by adampoczatek** [comment]
Same here, works on 5.3.0 though.

**Comment by trevoro** [comment]
Aha. So the issue is that we're not reading through the changes well enough

You have to ensure you install the `babel-preset-es2015` package using

`npm install --save-dev babel-preset-es2015` then update your .babelrc file to include

```
{
  "presets": ["es2015"]
}
```

then it started working again for me.

**Comment by dnldavidson** [comment]
Still won't work for even after following trevoro's advice.

**Comment by azizhk** [comment]
Getting this error even though I have `babel-preset-es2015` installed.

**Comment by allyrippley** [comment]
I was able to solve this by running `npm i core-js --save`, not sure if you can get away with just using it as a dev dependency. hope this saves someone some time

**Comment by julesmoretti** [comment]
Still not working...

trie the `npm i core-js --save`... nothing.



```
// gulp versions
[22:00:28] CLI version 1.2.2
[22:00:28] Local version 4.0.0-alpha.2
```

```
//gulpfile.babel.js
gulp.task('babel', (done) => {
	return gulp.src('app/js/components/*.js')
		.pipe(babel({"presets": ["es2015"]}))
		.pipe(gulp.dest('dist/js/components/'));
		done();
});
```

I have a file in the app/js/components called `helloworld.js` that looks like the one bellow and it hangs on the const declarations...

```
// helloworld.js
class StoryBox extends React.Component {

	const rightNow = new Date;
	const topicsList = ['HTML', 'JavaScript', 'React'];
	console.log('TIME NOW!!!!', now.toTimeString() );


	render() {
		return (
			<div>
				<h3>Story Box</h3>
				<p className="lead">
					Current time: { rightNow.toTimeString() }
				</p>
				<ul>
					{topicsList.map( topic => <li>{topic}</li> )}
				</ul>
			</div>
		);
	}
}

ReactDOM.render(
	<StoryBox />, document.getElementById('example')
);
```


```
//package.json
       ...
	"devDependencies": {
		"babel-preset-es2015": "^6.14.0",
		"gulp": "github:gulpjs/gulp#4.0",
		"gulp-babel": "^5.3.0",
```

```
//.babelrc
{
	"presets": ["es2015"]
}
```

Would love some final help with this.

**Comment by dominik0711** [comment]
Hi. I'm not able to transpile my es6 code to es5 due to the following error:

`Couldn't find preset "es2015" relative to directory`

This is my environment:
OS: OS X 
CLI version 1.2.2                                                                                                 
Local version 4.0.0-alpha.2

package.json (partial):
```
  "devDependencies": {
    "babel-preset-es2015": "^6.16.0",
    "browser-sync": "^2.7.7",
    "connect-history-api-fallback": "^1.1.0",
    "del": "^2.0.2",
    "es6-promise": "^3.1.2",
    "glob-all": "^3.0.1",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-babel": "^6.1.2",
...
```

I have the following project structure:
|-!deploy
|-build
|---components
|---helpers
|---node_modules
|---tasks
|-src
|---assets
|---components
|---js
|-----3rd
|-------jspdf
|-------lz-string
|-----ext-store
|-----mod
|---libs
|---style

My gulpfile is inside my **build** folder and from here I would like to transpile my JavaScript (es6) files sitting inside **src/js** folder to my **!deploy** folder.

I have in installed gulpv4, CLI1.2.2, babel-preset-es2015v6.16.0.

Why does gulp-babel reports: 

`Couldn't find preset "es2015" relative to directory "/Users/tester/Projects/XXX/src"`

**Comment by julesmoretti** [comment]
@dominik0711 not sure if this will help. But it might be one of 2 things (emphasis on the might)...

1. You might need these also installed using npm:
    "babel-core": "^6.14.0",
    "babel-loader": "^6.2.5",

2. You might need a .babelrc file in the root directory that looks like this:

```
{
	"presets": ["react", "es2015", "stage-0"],
	"env": {
		"development": {
			"presets": ["react-hmre"]
		}
	}
}
```

In your case it would probably just look like this:

```
{
	"presets": ["es2015"],
}
```

**Comment by brysonthor** [comment]
roasting my local node_modules folder and doing a fresh npm install fixed it for me.

**Comment by hzoo** [comment]
Closing for inactivity and seems like too many different issues.
